name: Deploy Pipelines - PROD

on:
  workflow_dispatch:
      
jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_deploy_pipelines.yaml@main
    name: Deploy on PROD
    secrets: inherit
    with:
      environment: 'prod'
      resource_group_name: 'io-p-shared-rg'
      app_name: 'io-p-public-fn'
      use_staging_slot: true
      use_private_agent: false
